---


# defaults file for cp-configure

base_pas_url: https://ec2-34-216-15-14.us-west-2.compute.amazonaws.com
cp_file: AAM-RHELinux-Intel64-Rls-v13.0.2.zip
cp_s3_bucket: citi-ansible-cp
vault_address: 54.184.200.65
cp_rpm: CARKaim-13.00.02.4.x86_64.rpm

#path defaults
base_path: /cp_install
aimparms_path: /var/tmp/aimparms
vault_ini_path: /etc/opt/CARKaim/vault/Vault.ini
admin_credfile_path: /cp_install/admin.cred
app_credfile_path: /etc/opt/CARKaim/vault/appprovideruser.cred
create_credfile_path: /cp_install/CreateCredFile
cp_rpm_path: /cp_install/CARKaim-13.00.02.4.x86_64.rpm

### ANSIBLE ADMINISTRATION ###
cp_ansible_directory_path: /etc/opt/CARK-ansible
cp_ansible_user_id_file: "{{ cp_ansible_directory_path }}/aimprov_user_id.txt" 
cp_ansible_account_id_file: "{{ cp_ansible_directory_path }}/aimprov_account_id.txt" 
sample_script_path: "{{ cp_ansible_directory_path }}/remote.sh"

#API logon
auth_type: Cyberark
logon_url: "https://ec2-34-216-15-14.us-west-2.compute.amazonaws.com/PasswordVault/WebServices/auth/{{ auth_type }}/CyberArkAuthenticationService.svc/Logon"
admin_user: administrator
admin_pw: CyberArk11@@

#UserAdd url

add_user_url: https://ec2-34-216-15-14.us-west-2.compute.amazonaws.com/PasswordVault/API/Users
new_cp_user: Prov_{{ansible_hostname}} 
new_cp_pw: CyberArk11@@
user_type: AppProvider

#DeleteUser url
delete_user_base: https://"{{ base_pas_url }}"/PasswordVault/API/Users/

#Account creation:

 
account_platform_type: UnixSSH
cyberark_account_name: account--{{ ansible_hostname }}
cyberark_account_type: password
cyberark_account_secret: Khan!Artist@

#Boolean

disable_gpg_check: true
logon_ssl_validation: no
