---


# defaults file for cp-configure
#INSERT CONFIG HERE

base_pas_url:  # e.g. https://ec2-34-216-15-14.us-west-2.compute.amazonaws.com
cp_file:    # e.g. AAM-RHELinux-Intel64-Rls-v13.0.2.zip
cp_s3_bucket: # assumes zip file is stored in an S3 bucket 
vault_address:  #e.g. 54.184.200.65
cp_rpm: CARKaim-13.00.02.4.x86_64.rpm
admin_user:   # e.g. administrator user for CyberArk Vault
admin_pw:  #e.g. Cyberark administrator password

#path defaults
base_path: /cp_install
aimparms_path: /var/tmp/aimparms
vault_ini_path: /etc/opt/CARKaim/vault/Vault.ini
admin_credfile_path: /cp_install/admin.cred
app_credfile_path: /etc/opt/CARKaim/vault/appprovideruser.cred
create_credfile_path: /cp_install/CreateCredFile
cp_rpm_path: /cp_install/"{{"

### ANSIBLE ADMINISTRATION ###
cp_ansible_directory_path: /etc/opt/CARK-ansible
cp_ansible_user_id_file: "{{ cp_ansible_directory_path }}/aimprov_user_id.txt" 
cp_ansible_account_id_file: "{{ cp_ansible_directory_path }}/aimprov_account_id.txt" 
sample_script_path: "{{ cp_ansible_directory_path }}/remote.sh"

#API logon
auth_type: Cyberark
logon_url: "https://"{{ base_pas_url }}"/PasswordVault/WebServices/auth/{{ auth_type }}/CyberArkAuthenticationService.svc/Logon"


#UserAdd url

add_user_url: https://"{{ base_pas_url }}"/PasswordVault/API/Users
new_cp_user: Prov_{{ansible_hostname}} 
new_cp_pw: CyberArk11@@
user_type: AppProvider

#DeleteUser url
delete_user_base: https://"{{ base_pas_url }}"/PasswordVault/API/Users/

#Account creation:

 
account_platform_type: UnixSSH
cyberark_account_name: account--{{ ansible_hostname }}
cyberark_account_type: password
cyberark_account_secret: BobL0blaw11@@!

#Boolean

disable_gpg_check: true
logon_ssl_validation: no
