    - name: Verify status of aimprv service initially
      command: systemctl status aimprv.service
      register: service_already_running
      ignore_errors: yes
      changed_when: false


    - debug: msg="status of service RC={{service_already_running.rc}}"

    - import_tasks: install.yaml
      when: (service_already_running.rc != 0)

    - import_tasks: uninstall.yaml
      when: (service_already_running.rc == 0)