
- name: Login to Vault API for Deletion
  uri:
    url: "{{ logon_url }}"
    method: POST
    body_format: json
    body:
      username: "{{ admin_user }}" 
      password: "{{ admin_pw }}"
      #v2 concurrent_sessions= " {{ concurrent_session_bool }} "
    validate_certs: "{{ logon_ssl_validation }}"
  register: login_json_results
- debug:
     var: login_json_results
- debug:
     var: "{{ 'aim_prov_user_id' }}"

- name: Set Login token
  set_fact: 
    ca_login_token: "{{ login_json_results.json.CyberArkLogonResult }}"
- debug:
     var: ca_login_token  

- name: Remove CP user from Vault
  uri: 
    url: "{{ base_pas_url }}/PasswordVault/API/Users/{{ aim_prov_user_id }}"
    method: DELETE
    validate_certs: "{{ logon_ssl_validation }}"
    headers:
      authorization: "{{ ca_login_token }}"
  register: remove_user_results

- debug:
     var: remove_user_results

- name: Remove the Apache package
  ansible.builtin.dnf:
    name: CARKaim
    state: absent

- name: Remove CP config files
  file:
    path: '/etc/opt/CARKaim'
    state: absent

- name: Remove AppProvider Confs
  file:
    path: '/var/opt/CARKaim'
    state: absent

- name: Remove AimParams File
  file:
    path: '/var/tmp/aimparms'
    state: absent
